### ISSUE TITLE
[bug]: Meta image not pulling despite being set

### ISSUE THREAD

**Issue by mylespalmer** [StudioCompanion/companion-studio#206]
## 🐛 Bug Report

The meta image isn't being pulled through on the team page (and maybe others) despite it being set in Sanity.

## To Reproduce

Visit here, or share the URL on slack: https://www.opengraph.xyz/url/https%3A%2F%2Fcompanion-studio-eta.vercel.app%2Fteam/

## Expected behavior

It should take the image from Sanity. Is it possible to also serve an asset that is optimised, rather than source? IE a compressed 1080 or something?

**Comment by joshuaellis** [comment]
This has not actually been set, because there are specific dimension requirements for an SEO image we're not able to use the image from PageCard. The dimensions required being 1200x630.

<img width="1453" alt="image" src="https://user-images.githubusercontent.com/37798644/169511237-308ec00c-0fc0-4c5f-84fb-4759e36df99b.png">

**Comment by mylespalmer** [comment]
Ahhh, page meta and page card, ok, got it — can we place `meta` at the bottom please?

**Comment by joshuaellis** [comment]
> Ahhh, page meta and page card, ok, got it — can we place `meta` at the bottom please?

sure!
