### ISSUE TITLE
Mux video compression

### ISSUE THREAD

**Issue by mylespalmer** [StudioCompanion/companion-studio#213]
[![Screenshot_2022-05-21_15-34-45.png](https://mrkr.io/s/62890695d368286d46f811eb/2)](https://mrkr.io/s/62890695d368286d46f811eb/0)

Is mux applying additional video compression on top of the uploaded videos, and if so, is this changeable?

---

**Source URL:** [https://companion-studio-eta.vercel.app/](https://companion-studio-eta.vercel.app/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62890695d368286d46f811ee_25208d3fea9b49ac)

<table><tr><td><strong>Browser</strong></td><td>Chrome Mobile 101.0.4951.64</td></tr><tr><td><strong>Screen Size</strong></td><td>1728 x 1117</td></tr><tr><td><strong>OS</strong></td><td>OS X 12.0.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1393 x 1000</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by joshuaellis** [comment]
I don't know a lot about video compression / encoding etc. but here's mux's information on it https://www.mux.com/encoding they do re-encode any video you provide because each video is streamed as opposed to a complete download, this therefore allows poorer quality videos to be shown when the required bandwidth is not available.

I don't believe from a code perspective there is anything we're doing incorrectly or different to other projects using MUX.
