### ISSUE TITLE
Button Hover States

### ISSUE THREAD

**Issue by mylespalmer** [StudioCompanion/companion-studio#217]
[![Screenshot_2022-05-22_21-03-10.png](https://mrkr.io/s/628aa50ecfba1a88fd15783d/2)](https://mrkr.io/s/628aa50ecfba1a88fd15783d/0)

The button hover states aren't great at the minute, getting the dimmed opacity.

Can we do something better? 

Perhaps it needs to go to filled brand colours instead?

---

**Source URL:** [https://companion-studio-eta.vercel.app/projects/do-lectures](https://companion-studio-eta.vercel.app/projects/do-lectures)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/628aa50ecfba1a88fd157840_cc2fdd45a3db9392)

<table><tr><td><strong>Browser</strong></td><td>Chrome 101.0.4951.64</td></tr><tr><td><strong>Screen Size</strong></td><td>1728 x 1117</td></tr><tr><td><strong>OS</strong></td><td>OS X 12.0.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1728 x 1000</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by joshuaellis** [comment]
What you're asking for would be to set the colors for each button on the site and therefore to have different colors per button. I think it's a bad idea because it would therefore confuse users through inconsistencies and to have it set in the CMS is just overkill because as the site grows this complexity grows with it especially since a button is a core piece it can be used in numerous ways.

IMO I would pick a color and apply it...

**Comment by mylespalmer** [comment]
In that case, rather than change opacity, can we change background colour like so?

Transition can remain as you have it.

https://codepen.io/mylespalmer/pen/dydVGyO
